"""Restructure documents and add document_results

Revision ID: 0e1b94ba2e10
Revises: bb652c2912c9
Create Date: 2026-07-29 21:49:44.577898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e1b94ba2e10'
down_revision: Union[str, Sequence[str], None] = 'bb652c2912c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.add_column('documents', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.String(length=512), nullable=False))
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    op.drop_column('documents', 'full_text')
    op.drop_column('documents', 'filename')
    op.drop_column('documents', 'file_url')
    op.drop_column('documents', 'total_pages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('total_pages', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('file_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('full_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'file_name')
    op.drop_column('documents', 'user_id')
    op.drop_table('document_results')
    # ### end Alembic commands ###
