"""Add index for document search

Revision ID: 9bdfaafd70e9
Revises: 0e1b94ba2e10
Create Date: 2026-07-29 22:05:36.231411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bdfaafd70e9'
down_revision: Union[str, Sequence[str], None] = '0e1b94ba2e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_file_name'), 'documents', ['file_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    # ### end Alembic commands ###
